env_id: 56f454da3195d51d008e665d

name: hound

processes:
  web:
    command: bundle exec puma -C config/puma.rb
    instances: 1
    memory: 450

  resque_high:
    command: env TERM_CHILD=1 RESQUE_TERM_TIMEOUT=8 QUEUE=* bundle exec rake resque:work
    instances: 2
    memory: 350

  resque_scheduler:
    command: bundle exec rake resque:scheduler
    instances: 1
    memory: 150

